/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        tertiary: "#6e5e0d",
        background: "#f9f9f9",
        "inverse-on-surface": "#f1f1f1",
        "surface-dim": "#dadada",
        "surface-container": "#eeeeee",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e8e8e8",
        surface: "#f9f9f9",
        "tertiary-fixed-dim": "#dcc66e",
        "on-background": "#1a1c1c",
        "on-tertiary-container": "#4b3f00",
        "on-primary-fixed": "#2f1500",
        "on-surface-variant": "#554336",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        error: "#ba1a1a",
        primary: "#8d4b00",
        "on-secondary-fixed": "#1c1b1b",
        "surface-tint": "#904d00",
        "tertiary-container": "#bfab56",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#c8c6c5",
        "primary-fixed": "#ffdcc3",
        "surface-container-highest": "#e2e2e2",
        "primary-fixed-dim": "#ffb77d",
        "surface-container-low": "#f3f3f3",
        "inverse-primary": "#ffb77d",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#f9e287",
        "on-primary-fixed-variant": "#6e3900",
        "secondary-container": "#e2dfde",
        "inverse-surface": "#2f3131",
        "on-secondary-fixed-variant": "#474746",
        "outline-variant": "#dbc2b0",
        "primary-container": "#b15f00",
        "on-tertiary-fixed-variant": "#534600",
        "on-secondary-container": "#636262",
        "on-primary-container": "#fffbff",
        "surface-bright": "#f9f9f9",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#221b00",
        outline: "#887364",
        "surface-variant": "#e2e2e2",
        "secondary-fixed": "#e5e2e1",
        secondary: "#5f5e5e",
        "on-surface": "#1a1c1c",
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "label-bold": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
        "headline-sm": ["Playfair Display", "serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Playfair Display", "serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-bold": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "headline-md": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["24px", { lineHeight: "1.3", fontWeight: "700" }],
        "display-lg-mobile": ["36px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
      },
      spacing: {
        gutter: "20px",
        "margin-mobile": "16px",
        base: "4px",
        sm: "16px",
        "margin-desktop": "48px",
        md: "24px",
        xs: "8px",
        xl: "64px",
        lg: "40px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
}
